version: '3'

services:
  app-backend-qr-prod:
    build:
      dockerfile: Dockerfile.backend.prod
      context: ./ProyectoQR-Backend
    image: image-app-backend-qr-prod
    container_name: ctn-app-backend-qr-prod
    ports:
    - "8001:8001"
    - "8000:8000"
    environment:
      - MONGO_HOST=clusterdev.hkpq9.mongodb.net
      - MONGO_PORT=27017
      - MONGO_USERNAME=mongodbdev
      - MONGO_PASSWORD=mongobddev
    volumes:
      - ./ProyectoQR-Backend/src:/app/backend/src
      - ./ProyectoQR-Backend/certs:/app/backend/certs
    restart: unless-stopped
    networks:
      - net-app-qr-prod

  app-frontend-qr-prod:
    build:
      dockerfile: Dockerfile.frontend.prod
      context: ./ProyectoQR-Frontend
    image: image-app-frontend-qr-prod
    container_name: ctn-app-frontend-qr-prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ProyectoQR-Frontend/webserver/log/access.log:/var/log/nginx/access.log
      - ./ProyectoQR-Frontend/webserver/log/error.log:/var/log/nginx/error.log
      - ./ProyectoQR-Frontend/webserver/default.conf:/etc/nginx/conf.d/default.conf
      - ./ProyectoQR-Frontend/webserver/certbot-etc:/etc/letsencrypt
      - ./ProyectoQR-Frontend/webserver/certbot-var:/var/lib/letsencrypt
    depends_on:
      - app-backend-qr-prod
    networks:
      - net-app-qr-prod

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./ProyectoQR-Frontend/webserver/certbot-etc:/etc/letsencrypt
      - ./ProyectoQR-Frontend/webserver/certbot-var:/var/lib/letsencrypt
      - ./ProyectoQR-Frontend/build:/usr/share/nginx/html
    depends_on:
      - app-frontend-qr-prod
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email erickmga123@gmail.com --agree-tos --no-eff-email --staging -d latam-strategy.com 


networks:
  net-app-qr-prod: