version: '3.1'

services:
  app-frontend-qr-prod:
    build:
      dockerfile: Dockerfile.frontend.prod
      context: ./ProyectoQR-Frontend
    image: image-app-frontend-qr-prod
    container_name: ctn-app-frontend-qr-prod
    ports:
    - "80:80"
    restart: always
    networks:
      - net-app-qr-prod
    volumes:
       - ./ProyectoQR-Frontend/src:/app/frontend/src
       - ./ProyectoQR-Frontend/public:/app/frontend/public
      
  app-backend-qr-prod:
    build:
      dockerfile: Dockerfile.backend.prod
      context: ./ProyectoQR-Backend
    image: image-app-backend-qr-prod
    container_name: ctn-app-backend-qr-prod
    ports:
    - "8000:8000"
    - "8001:8001"
    environment:
      - MONGO_HOST=clusterdev.hkpq9.mongodb.net
      - MONGO_PORT=27017
      - MONGO_USERNAME=mongodbdev
      - MONGO_PASSWORD=mongobddev
    restart: always
    networks:
      - net-app-qr-prod
    volumes:
      - ./ProyectoQR-Backend/src:/app/backend/src

networks:
  net-app-qr-prod:
